apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  AWS_REGION: <your region>
  Dequeueable__QueueUrl: <your queue url>
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secrets
data:
  AWS_ACCESS_KEY_ID: <your encoded key>
  AWS_SECRET_ACCESS_KEY: <your encoded secret>
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID
    name: test-secrets
    key: AWS_ACCESS_KEY_ID
  - parameter: awsSecretAccessKey
    name: test-secrets
    key: AWS_SECRET_ACCESS_KEY
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: queuejob-consumer
  namespace: default
spec:
  jobTargetRef:
    template:
      spec:
        containers:
          - name: queuejob-executor
            image: lenndewolten/dequeueable:aws-sqs-samplejob-v1
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: test-config
              - secretRef:
                  name: test-secrets
        restartPolicy: Never
    backoffLimit: 4
  pollingInterval: 60
  maxReplicaCount: 1
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: keda-trigger-auth-aws-credentials
      metadata:
        queueURL: <your queue url>
        queueLength: "5"
        awsRegion: <your region>
        identityOwner: pod
