apiVersion: v1
kind: ConfigMap
metadata:
  name: queuefunction-config
data:
  # Only for demo purpose how to use the connection string, you should use secrets!
  WebHost__ConnectionString: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://storage-azurite-service.default:10000/devstoreaccount1;QueueEndpoint=http://storage-azurite-service.default:10001/devstoreaccount1;TableEndpoint=http://storage-azurite-service.default:10002/devstoreaccount1;
  WebHost__QueueName: "testqueue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queuefunction-deployment
  labels:
    app: queuefunction-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queuefunction-deployment
  template:
    metadata:
      labels:
        app: queuefunction-deployment
    spec:
      containers:
      - name: queuefunction-executor
        image: lenndewolten/webjobs:samplefunction-v1
        imagePullPolicy: Always
        envFrom:
            - configMapRef:
                name: queuejob-consumer