apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  AWS_REGION: <your region>
  Dequeueable__QueueUrl: <your queue url>
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secrets
data:
  AWS_ACCESS_KEY_ID: <your encoded key>
  AWS_SECRET_ACCESS_KEY: <your encoded secret>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queuelistener-deployment
  labels:
    app: queuelistener-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queuelistener-deployment
  template:
    metadata:
      labels:
        app: queuelistener-deployment
    spec:
      containers:
        - name: queuelistener-executor
          image: lenndewolten/dequeueable:aws-sqs-samplelistener-v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: test-config
            - secretRef:
                  name: test-secrets
