apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-azurite-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      app: storage-azurite
  template:
    metadata:
      labels:
        tier: backend
        app: storage-azurite
    spec:
      containers:
      - name: storage-azurite-container
        image: mcr.microsoft.com/azurestorage-azurite
        ports:
        - containerPort: 10000
        - containerPort: 10001
        - containerPort: 10002
---
apiVersion: v1
kind: Service
metadata:
  name: storage-azurite-service
spec:
  type: NodePort
  ports:
  - name: storage-azurite-blobs
    port: 10000
    targetPort: 10000 
  - name: storage-azurite-queues
    port: 10001
    targetPort: 10001
  - name: storage-azurite-tables
    port: 10002
    targetPort: 10002
  selector:
    app: storage-azurite