apiVersion: v1
kind: ConfigMap
metadata:
  name: queuelistener-config
data:
  # Only for demo purpose how to use the connection string, you should use secrets!
  Dequeueable__ConnectionString: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://storage-azurite-service.default:10000/devstoreaccount1;QueueEndpoint=http://storage-azurite-service.default:10001/devstoreaccount1;TableEndpoint=http://storage-azurite-service.default:10002/devstoreaccount1;
  Dequeueable__QueueName: "testqueue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queuelistener-deployment
  labels:
    app: queuelistener-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queuelistener-deployment
  template:
    metadata:
      labels:
        app: queuelistener-deployment
    spec:
      containers:
        - name: queuelistener-executor
          image: lenndewolten/dequeueable:azure-queue-storage-samplelistener-v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: queuelistener-config
