on:
  pull_request:
    branches:
      - "main"
    paths:
      - "lib/Dequeueable.AzureQueueStorage/**"
      - "tests/Dequeueable.AzureQueueStorage.**/"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x.x"
      - name: Materialize Signing Key
        id: write_sign_key_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "Dequeueable.snk"
          encodedString: ${{ secrets.SIGNING_KEY }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
        env:
          DOTNET_BUILD_ARGS: --property:AssemblyOriginatorKeyFile=${{ steps.write_sign_key_file.outputs.filePath }} --property:SignAssembly=true
      - name: Test
        run: dotnet test --no-restore --verbosity minimal
